### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/scratch-olympics-weightlifter#1]
Hi @LornaLynch and @lauraclay 
Could I get a copy edit on this if either of you have time on **Friday**. No real rush, but it would be nice to get it our before the kiddies all go back to school

**Comment by LornaLynch** [comment]
Making a start now.

**Comment by MarcScott** [comment]
You're awedome. Really no rush though.

**Comment by LornaLynch** [comment]
I may not get it all done tonight, but I'll let @lauraclay where I stop in case she wants to carry on. We're hanging on for bedtime at the moment...

**Comment by LornaLynch** [comment]
Also, I removed the link to the cover image from the worksheet: I don't think it's needed?

**Comment by LornaLynch** [comment]
Around line 37 of worksheet 1, does the screencap match the instructions? Sorry if I'm being thick, but it looks like it doesn't.

**Comment by MarcScott** [comment]
Yep - my stupid error - fixed now

**Comment by LornaLynch** [comment]
Cheers!

**Comment by LornaLynch** [comment]
Just checking again: should progress be set to to zero here or to one? It's zero in this screenshot, so I wondered about changing it in the text, but elsewhere it is 1 at the start of the program.

**Comment by MarcScott** [comment]
It should be 1. I'll fix. I get confused easily :smile: 
Well done on the technical edit.

**Comment by LornaLynch** [comment]
No worries! I'm at the end of Worksheet 1 (though I should probably give it another check after the boys are in bed) so if @lauraclay happens to be free, WS 2 is up for grabs. Otherwise I'll get it in a moment.

**Comment by MarcScott** [comment]
Fixed the image problem
Leave it for tonight and have some quiet time - it can wait until tomorrow. I'm going to watch a movie with the boy, so really no rush.
Signing off now,
Thanks

**Comment by LornaLynch** [comment]
If you're sure? I think there's a beer with my name on it.

**Comment by lauraclay** [comment]
Just saw this - will go over the resource now.

**Comment by lauraclay** [comment]
The copy edit is done, though I just wanted to check if we're okay with making an exception to the style guide here. We tend to avoid using the verb 'hit' for buttons/keys in favour of 'press', but since this game basically requires you to hit them it seems wrong to change it. Any synonyms would be welcome!

**Comment by MarcScott** [comment]
Cheers @lauraclay. We could use the word **mash** I suppose, but I'm not overly bothered. If you want to revert it back to press I would have no objections.

**Comment by lauraclay** [comment]
I think in this case I'm happy to make this a 'stet' and leave it as is 😄

**Comment by LornaLynch** [comment]
Just noticed the link to cover.gif in the README doesn't seem to be working, @MarcScott

**Comment by MarcScott** [comment]
fixed - thanks
